version: '3.8'

services:
  api:
    image: dev-collab-api:latest
    # restart: always
    ports:
      - 80:8080
    expose:
      - 8080
    networks:
      - default

networks:
  default:
    driver: bridge
