name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing run
        run: echo "helloworld"
          
