name: api-build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: npm install
        working-directory: ./apps/dev-collab-api
        run: npm i
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./apps/dev-collab-api/

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy with PM2
        working-directory: .
        run: |
          pm2 delete dev-collab-api || true
          
          # Start new process
          pm2 start npm --name dev-collab-api start:prod 8080
          
          # Save PM2 configuration
          pm2 save